// Code generated by golex utility;
// This code is present a default handling of tokens;
// YOU CAN EDIT IT IF YOU NEED.
package main

import (
	"bufio"
	"fmt"
	"github.com/OkDenAl/golex/examples/lab1.2/golexgen"
	"log"
	"os"
)

type Handler struct {
	golexgen.HandlerBase
}

func main() {
	filePath := "./examples/lab1.2/test.txt"

	file, err := os.Open(filePath)
	if err != nil {
		log.Fatal(err.Error())
	}
	defer file.Close()

	scn := golexgen.NewScanner(*bufio.NewReader(file), &Handler{})

	t := scn.NextTokenOneAutomata()
	for t.Tag() != golexgen.EOP {
		fmt.Println(t.String())
		t = scn.NextTokenOneAutomata()
	}
}
